- name: Deploy etcd backup configuration
  import_tasks: deploy.yml
  when: not teardown | default(false)

- name: Teardown etcd backup configuration
  import_tasks: teardown.yml
  when: teardown | default(false)
  