- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

- name: Teardown build prune objects
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    resource_definition: "{{ lookup('file', 'prune-builds.yml') }}"
    validate:
      fail_on_error: yes
      strict: yes
    state: absent

- name: Teardown image prune objects
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    resource_definition: "{{ lookup('template', 'prune-images.yml.j2') }}"
    validate:
      fail_on_error: yes
      strict: yes
    state: absent

- name: Teardown deployment prune objects
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    resource_definition: "{{ lookup('file', 'prune-deployments.yml') }}"
    validate:
      fail_on_error: yes
      strict: yes
    state: absent