- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

- name: get a list of pods from any namespace
  k8s_info:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    kind: Pod
    validate_certs: no
  register: pod_list

- name: print pod list
  debug:
    var: pod_list

- name: Get cluster operators
  shell: "oc get co
          --token {{ k8s_auth_results.k8s_auth.api_key }}"
  register: co_list

- name: print cluster operators
  debug:
    var: co_list