- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

# Prepare Image Registry

- name: Create PVC for image registry
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    validate_certs: no
    definition: "{{ lookup('file', 'image-registry-pvc.yml') }}"

# Configure PVC storage provided the variable image_registry_emptydir variable
# is false.
- name: Configure PVC storage for Image Registry
  block:
    - name: Remove emptyDir storage if configured
      shell: >-
        oc patch configs.imageregistry.operator.openshift.io/cluster
        --type json
        --patch='[{"op":"remove","path":"/spec/storage/emptyDir"}]'
        --token {{ k8s_auth_results.k8s_auth.api_key }}

    - name: Assign pvc to image registry if it is not already assigned
      shell: >-
        oc patch configs.imageregistry.operator.openshift.io/cluster
        --type merge
        --patch='{"spec":{"storage":{"pvc":{"claim":""}}}}'
        --token {{ k8s_auth_results.k8s_auth.api_key }}

- name: Change image registry ManagementState
  shell: >-
    oc patch configs.imageregistry.operator.openshift.io/cluster
    --type merge
    --patch='{"spec":{"managementState":"Managed"}}'
    --token {{ k8s_auth_results.k8s_auth.api_key }}