- fail:
    msg: "Make sure we've authenticated to the cluster before running this role"
  when: k8s_auth_results.k8s_auth.api_key is not defined

- name: Configure emptyDir storage for Image Registry
  shell: >-
    oc patch configs.imageregistry.operator.openshift.io/cluster
    --type merge
    --patch='{"spec":{"storage":{"emptyDir":{}}}}'
    --token {{ k8s_auth_results.k8s_auth.api_key }}

- name: Remove PVC for image registry
  k8s:
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: absent
    validate_certs: no
    definition: "{{ lookup('file', 'image-registry-pvc.yml') }}"

- name: Change image registry ManagementState
  shell: >-
    oc patch configs.imageregistry.operator.openshift.io/cluster
    --type merge
    --patch='{"spec":{"managementState":"Removed"}}'
    --token {{ k8s_auth_results.k8s_auth.api_key }}